name: Publish Modpack to Modrinth

on:
  release:
    types: [published] # Chỉ kích hoạt khi bạn bấm nút Publish Release trên web
    workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Modpack
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 'IJyTMHoI'
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          # Lấy chính xác tên và tag bạn vừa gõ trên giao diện web GitHub
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          
          version-type: release
          files: '*.mrpack'
