name: Publish Modpack to Modrinth

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # BƯỚC QUAN TRỌNG: Tải file từ Release vừa tạo về máy chủ GitHub Action
      - name: Download Release Asset
        uses: dsayling/download-release-asset@v1
        with:
          # Lấy chính cái release vừa kích hoạt workflow này
          releaseId: ${{ github.event.release.id }}
          # Tìm file có đuôi .mrpack trong Release đó
          assetName: '*.mrpack' 
          # Tải về thư mục hiện tại
          downloadPath: './'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Modpack to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 'IJyTMHoI'
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          # Lấy thông tin từ Release của GitHub
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          
          version-type: release
          # Bây giờ file đã được tải về thư mục gốc nên dòng này sẽ chạy đúng
          files: '*.mrpack' 
          loaders: fabric
          game-versions: 1.20.1
